# DIP Lab 1: Basic Introduction to OpenCV

For this course you'll be using two main tools namely Matlab and OpenCV. OpenCV is an opensource Computer Vision library that is available for a couple of programming languages including python. The library provides with a lot comples and basic functionalities in the domain of Computer Vision.<br>

In this lab we will be exploring some basic functionalities available in OpenCV

## Installing OpenCV in Python

In order to install OpenCV you may runt he following command in your command prompt: <br>

> ```pip install opencv-python``` <br>
 
An additional package that you can install is: <br>

> ```pip install opencv-contrib-python```

## Importing Libraries


We will be importing OpenCV as cv2 and numpy. Numpy is very essential for OpenCV since every image loaded is in a numpy array.

In [5]:
import cv2
import numpy as np

## Reading Image

Reading an image via OpenCV is very easy just call the
```cv2.imread()``` function and give it the path to the image. It can read almost all formats. <br>

By default OpenCV reads all images as colored. The channels in the image are in the order BGR (Blue Green Red), which is unconventional to RGB (Red Green Blue). <br>

In order to read the image in some other color scheme such as grayscale can be done by passing another parameter to the imread function. Check out ```cv2.imread()``` documentation online to see more arguments.

In [26]:
img_clr = cv2.imread("lenna.png") # reading in default color scheme i.e. BGR (colored)
img_gray = cv2.imread("lenna.png", cv2.IMREAD_GRAYSCALE) # reading the same image in grayscale

## Image Shape (Spatial Resolution)

Every image read via OpenCV is a numpy array whose dimensions depend on the color channels of the image. An image would be atleast a 2D matrix represented by 2D Numpy arrays (lists within lists).

The following code example shows the sizes of both the colored and grayscale image. Upon running the cell below you'll see tuples indicating the shape of the image.

For the colored image the tuple is of length 3, in which the first number represents the height (no. of rows of matrix), the second represents the width (no. of columns of matrix) and the third represents the no. of color channels which in the case of are 3 (BGR).

For the grayscale image the two numbers represent the height and width of the image. Since the channels for a grayscale image is 1 there is no third number.

In [7]:
print("Shape of colored image: {}".format(img_clr.shape))
print("Shape of grayscale image: {}".format(img_gray.shape))

Shape of colored image: (512, 512, 3)
Shape of grayscale image: (512, 512)


## Assessing Channel Value for Colored and Grayscale image

The result of the code segment below will bombard your screen with a bunch of number, so lets try to make some sense out of these numbers.

Each set of the inner most array such as ```[125 137 226]``` represents the color intensity of each pixel. Every color in the computer is made up from a mixture of some basic colors. For OpenCV these are BGR (Blue Green Red), hence ```125``` is the red color intensity, ```137``` intensity for Green and ```226``` intensity of blue.

The values of these pixels are always between 0 and 255 (inclusive). 0 being the darkest and 255 being the lightest.

In [8]:
# printing image matrix for colored image
print(img_clr)

[[[125 137 226]
  [125 137 226]
  [133 137 223]
  ...
  [122 148 230]
  [110 130 221]
  [ 90  99 200]]

 [[125 137 226]
  [125 137 226]
  [133 137 223]
  ...
  [122 148 230]
  [110 130 221]
  [ 90  99 200]]

 [[125 137 226]
  [125 137 226]
  [133 137 223]
  ...
  [122 148 230]
  [110 130 221]
  [ 90  99 200]]

 ...

 [[ 60  18  84]
  [ 60  18  84]
  [ 58  27  92]
  ...
  [ 84  73 173]
  [ 76  68 172]
  [ 79  62 177]]

 [[ 57  22  82]
  [ 57  22  82]
  [ 62  32  96]
  ...
  [ 79  70 179]
  [ 81  71 181]
  [ 81  74 185]]

 [[ 57  22  82]
  [ 57  22  82]
  [ 62  32  96]
  ...
  [ 79  70 179]
  [ 81  71 181]
  [ 81  74 185]]]


The output of the code snippet below would yeild quite less numbers as compared to the previous one. This is because for grayscale there is only one color channel, since grayscale images are made up of shades of gray. Here as you see below each pixel is only made of a single number which represents the intensity of gray 0 being black and 255 being white. Here too value are between 0 and 255 inclusive.

In [9]:
print(img_gray)

[[169 169 168 ... 175 162 138]
 [169 169 168 ... 175 162 138]
 [169 169 168 ... 175 162 138]
 ...
 [ 53  53  59 ... 115 112 114]
 [ 53  53  64 ... 117 118 122]
 [ 53  53  64 ... 117 118 122]]


## Accessing Pixel values via Indexing

Since image loaded using OpenCV is a Numpy array, elements within a Numpy array can be accessed via indexing supported by Numpy, see the example below.

More details on Numpy Indexing can be found on this [Link](https://numpy.org/doc/stable/reference/arrays.indexing.html)

In [10]:
print("A pixel value from BGR image: {}".format(img_clr[20,20]))
print("A pixel value from grayscale image: {}".format(img_gray[20,20]))

A pixel value from BGR image: [107 125 226]
A pixel value from grayscale image: 162


## Displaying Image

Displaying an image preloaded using ```cv2.imread()``` is very easy. The function to show the image is ```cv2.imshow()``` where the first argument is the name of the window and the second is the image variable.
```cv2.imshow()``` itself is not enough to properly to display the image, ```cv2.waitKey()``` is necessary to stop the image window to close instantly and ```cv2.destroyAllWindows()``` is used to close the image window once a key is pressed to stop waiting.

In [15]:
# showing colored image
cv2.imshow('colored image', img_clr)
cv2.waitKey() # to hold the image window 
cv2.destroyAllWindows()

# showing grayscale image
cv2.imshow('grayscale image', img_gray)
cv2.waitKey()
cv2.destroyAllWindows()

## Task 1:
* __Read a colored image__
* ___Convert it to grayscale___
* ___write the image as JPEG___

#### Hint: use function ```cv2.cvtColor()``` and ```cv2.imwrite()```


In [16]:
# write your code for Task 1 below

## Task 2:
* __Read a colored image__
* __Separate all the channels in different variables__
* __show these different channels__
* __The expected images for these channels would be grayscale with different intensities, why is this so? and how can you make them show their color channels?__
* __show different channels of the image colored (not grayscale)__

In [ ]:
# write your code for Task 2 below

## Drawing Functions

OpenCV library provides us with some of the basic drawing functions. These basic drawing function include things like lines, circles, text etc.

The origin of canvas for OpenCV start from the top left left corner. The x-axis progresses downwards and y-axis towards right.

Play with the code segments below to see for yourself how the OpenCV acts. While you are at it try to change coordinates, color, line width etc.

### Line

In [27]:
line_color = (0, 255, 0) # green
start_coord = (0, 0) # starting coordinate
end_coord = (50, 150) # ending coordinate
line_width = 20 # value in pixels

img_copy = img_clr.copy() # creating a copy of the image

# drawing line on image
cv2.line(img_copy, start_coord, end_coord, line_color, line_width)

#showing image
cv2.imshow("line on bgr image", img_copy)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Rectangle

In [30]:
line_color = (255, 0, 0) # blue
start_coord = (50, 120) # starting coordinate
end_coord = (450, 350) # ending coordinate
line_width = 20 # value in pixels

img_copy = img_clr.copy() # creating a copy of the image

# drawing rectangle on image
cv2.rectangle(img_copy, start_coord, end_coord, line_color, line_width)

#showing image
cv2.imshow("rectangle on bgr image", img_copy)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Text

In [35]:
font = cv2.FONT_HERSHEY_SIMPLEX # selecting font face
font_color = (125, 125, 0) # some color 
start_coord = (50, 120) # starting coordinate
thickness = 10 # value in pixels
font_scale = 2 # adjusts the size of the font
text_to_write = "hello world"

img_copy = img_clr.copy() # creating a copy of the image

# adding text
cv2.putText(img_copy, text_to_write, start_coord, font, font_scale, font_color, thickness)

#showing image
cv2.imshow("text on bgr image", img_copy)
cv2.waitKey(0)
cv2.destroyAllWindows()